INSERT INTO categories (category) VALUES
('branding'),
('education'),
('customers'),
('career'),
('boards'),
('company building'),
('hiring'),
('managing'),
('marketing'),
('mna'),
('pricing'),
('productivity'),
('sales'),
('strategy'),
('sustainability'),
('teams')